const dedupeTerms = (terms: string[]) => {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const raw of terms) {
    const term = raw.trim();
    if (!term) continue;
    const key = term.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    result.push(term);
  }
  return result;
};

export const MEDICAL_SPECIALTY_TERMS = [
  "allergy",
  "allergy and immunology",
  "anesthesiology",
  "bariatric medicine",
  "cardiology",
  "clinical pharmacology",
  "critical care",
  "dermatology",
  "emergency medicine",
  "endocrinology",
  "family medicine",
  "gastroenterology",
  "geriatrics",
  "hematology",
  "hospital medicine",
  "infectious disease",
  "internal medicine",
  "interventional radiology",
  "medical oncology",
  "nephrology",
  "neurology",
  "neurosurgery",
  "obstetrics",
  "gynecology",
  "obstetrics and gynecology",
  "occupational medicine",
  "ophthalmology",
  "orthopedic surgery",
  "otolaryngology",
  "palliative care",
  "pain medicine",
  "pathology",
  "pediatrics",
  "physical medicine and rehabilitation",
  "plastic surgery",
  "psychiatry",
  "pulmonology",
  "radiation oncology",
  "radiology",
  "rheumatology",
  "sleep medicine",
  "sports medicine",
  "surgery",
  "thoracic surgery",
  "transplant hepatology",
  "trauma surgery",
  "surgical oncology",
  "maternal fetal medicine",
  "reproductive endocrinology",
  "reproductive medicine",
  "reproductive immunology",
  "addiction medicine",
  "adolescent medicine",
  "clinical genetics",
  "genomic medicine",
  "pediatric cardiology",
  "pediatric neurology",
  "pediatric surgery",
  "neonatology",
  "hematology oncology",
  "interventional cardiology",
  "electrophysiology",
  "advanced heart failure",
  "heart transplant",
  "inpatient psychiatry",
  "consult liaison psychiatry",
  "child and adolescent psychiatry",
  "forensic psychiatry",
  "sleep neurology",
  "head and neck surgery",
  "retina specialist",
  "glaucoma specialist",
  "cornea specialist",
  "female pelvic medicine",
  "urogynecology",
  "wound care",
  "pain management",
  "hospice and palliative medicine",
  "clinical informatics",
  "preventive medicine",
  "urgent care",
  "urology",
  "vascular surgery",
];

export const BIOLOGIC_AND_ADVANCED_THERAPY_TERMS = [
  "adalimumab",
  "Humira",
  "amgevita",
  "hyrimoz",
  "infliximab",
  "Remicade",
  "Inflectra",
  "Renflexis",
  "golimumab",
  "Simponi",
  "certolizumab pegol",
  "Cimzia",
  "etanercept",
  "Enbrel",
  "ixekizumab",
  "Taltz",
  "secukinumab",
  "Cosentyx",
  "brodalumab",
  "Siliq",
  "ustekinumab",
  "Stelara",
  "guselkumab",
  "Tremfya",
  "risankizumab",
  "Skyrizi",
  "tildrakizumab",
  "Ilumya",
  "vedolizumab",
  "Entyvio",
  "ustekinumab IV",
  "natalizumab",
  "Tysabri",
  "ocrelizumab",
  "Ocrevus",
  "ofatumumab",
  "Kesimpta",
  "rituximab",
  "Rituxan",
  "Truxima",
  "Ruxience",
  "obinutuzumab",
  "Gazyva",
  "belimumab",
  "Benlysta",
  "anifrolumab",
  "Saphnelo",
  "tocilizumab",
  "Actemra",
  "sarilumab",
  "Kevzara",
  "abatacept",
  "Orencia",
  "anakinra",
  "Kineret",
  "mepolizumab",
  "Nucala",
  "reslizumab",
  "Cinqair",
  "benralizumab",
  "Fasenra",
  "dupilumab",
  "Dupixent",
  "omalizumab",
  "Xolair",
  "tezepelumab",
  "Tezspire",
  "tralokinumab",
  "Adbry",
  "lebrikizumab",
  "Ebglyss",
  "evolocumab",
  "Repatha",
  "alirocumab",
  "Praluent",
  "inclisiran",
  "Leqvio",
  "semaglutide",
  "Ozempic",
  "Wegovy",
  "Rybelsus",
  "tirzepatide",
  "Mounjaro",
  "Zepbound",
  "liraglutide",
  "Victoza",
  "Saxenda",
  "dulaglutide",
  "Trulicity",
  "exenatide",
  "Byetta",
  "Bydureon",
  "canakinumab",
  "Ilaris",
  "eculizumab",
  "Soliris",
  "ravulizumab",
  "Ultomiris",
  "teplizumab",
  "Tzield",
  "upadacitinib",
  "Rinvoq",
  "tofacitinib",
  "Xeljanz",
  "baricitinib",
  "Olumiant",
  "deucravacitinib",
  "Sotyktu",
  "apremilast",
  "Otezla",
  "sotorasib",
  "Lumakras",
  "adagrasib",
  "Krazati",
  "pembrolizumab",
  "Keytruda",
  "nivolumab",
  "Opdivo",
  "atezolizumab",
  "Tecentriq",
  "durvalumab",
  "Imfinzi",
  "ipilimumab",
  "Yervoy",
  "trastuzumab",
  "Herceptin",
  "pertuzumab",
  "Perjeta",
  "bevacizumab",
  "Avastin",
  "ranibizumab",
  "Lucentis",
  "faricimab",
  "Vabysmo",
  "aflibercept",
  "Eylea",
  "romosozumab",
  "Evenity",
  "denosumab",
  "Prolia",
  "Xgeva",
  "teriparatide",
  "Forteo",
  "abaloparatide",
  "Tymlos",
  "mavacamten",
  "Camzyos",
  "sotatercept",
  "Winrevair",
  "epcoritamab",
  "Epkinly",
  "elranatamab",
  "Elrexfio",
  "teclistamab",
  "Tecvayli",
  "idecabtagene vicleucel",
  "Abecma",
  "ciltacabtagene autoleucel",
  "Carvykti",
  "tisagenlecleucel",
  "Kymriah",
  "axicabtagene ciloleucel",
  "Yescarta",
  "brexucabtagene autoleucel",
  "Tecartus",
  "lisocabtagene maraleucel",
  "Breyanzi",
  "isatuximab",
  "Sarclisa",
  "daratumumab",
  "Darzalex",
  "blinatumomab",
  "Blincyto",
  "inotuzumab ozogamicin",
  "Besponsa",
  "glofitamab",
  "Columvi",
  "mosunetuzumab",
  "Lunsumio",
  "bimekizumab",
  "Bimzelx",
  "roflumilast foam",
  "Zoryve",
  "mirikizumab",
  "Omvoh",
  "deucravacitinib",
  "Sotyktu",
  "risankizumab-rzaa",
  "adalimumab-adaz",
  "Hyrimoz",
  "adalimumab-atto",
  "Amjevita",
  "adalimumab-fkjp",
  "Hulio",
  "adalimumab-afzb",
  "Abrilada",
  "adalimumab-aacf",
  "Idacio",
  "infliximab-dyyb",
  "Inflectra",
  "infliximab-abda",
  "Renflexis",
  "infliximab-axxq",
  "Avsola",
  "etanercept-szzs",
  "Erelzi",
  "etanercept-ykro",
  "Eticovo",
  "tocilizumab-aazg",
  "Tyenne",
  "rituximab-pvvr",
  "Ruxience",
  "rituximab-abbs",
  "Truxima",
  "trastuzumab-dkst",
  "Ogivri",
  "trastuzumab-pkrb",
  "Herzuma",
  "bevacizumab-awwb",
  "Mvasi",
  "bevacizumab-bvzr",
  "Zirabev",
];

export const COMMON_MEDICATION_TERMS = [
  "acetaminophen",
  "ibuprofen",
  "naproxen",
  "aspirin",
  "diclofenac",
  "meloxicam",
  "celecoxib",
  "ketorolac",
  "tramadol",
  "hydrocodone",
  "oxycodone",
  "morphine",
  "fentanyl",
  "methadone",
  "buprenorphine",
  "gabapentin",
  "pregabalin",
  "cyclobenzaprine",
  "tizanidine",
  "baclofen",
  "prednisone",
  "methylprednisolone",
  "dexamethasone",
  "hydrocortisone",
  "metformin",
  "insulin glargine",
  "Lantus",
  "insulin lispro",
  "Humalog",
  "insulin aspart",
  "NovoLog",
  "empagliflozin",
  "Jardiance",
  "dapagliflozin",
  "Farxiga",
  "canagliflozin",
  "Invokana",
  "pioglitazone",
  "glipizide",
  "glyburide",
  "sitagliptin",
  "Januvia",
  "linagliptin",
  "Tradjenta",
  "lisinopril",
  "losartan",
  "valsartan",
  "olmesartan",
  "amlodipine",
  "nifedipine",
  "hydrochlorothiazide",
  "chlorthalidone",
  "furosemide",
  "spironolactone",
  "metoprolol",
  "carvedilol",
  "atenolol",
  "propranolol",
  "diltiazem",
  "verapamil",
  "atorvastatin",
  "rosuvastatin",
  "simvastatin",
  "pravastatin",
  "ezetimibe",
  "fenofibrate",
  "omega-3 acid ethyl esters",
  "warfarin",
  "apixaban",
  "Eliquis",
  "rivaroxaban",
  "Xarelto",
  "dabigatran",
  "Pradaxa",
  "edoxaban",
  "Savaysa",
  "clopidogrel",
  "ticagrelor",
  "Brilinta",
  "prasugrel",
  "Effient",
  "nitroglycerin",
  "isosorbide mononitrate",
  "omeprazole",
  "pantoprazole",
  "esomeprazole",
  "famotidine",
  "sucralfate",
  "ondansetron",
  "metoclopramide",
  "promethazine",
  "dicyclomine",
  "loperamide",
  "polyethylene glycol",
  "senna",
  "docusate",
  "lactulose",
  "levothyroxine",
  "methimazole",
  "propylthiouracil",
  "albuterol",
  "levalbuterol",
  "ipratropium",
  "tiotropium",
  "umeclidinium",
  "fluticasone",
  "budesonide",
  "salmeterol",
  "formoterol",
  "montelukast",
  "azithromycin",
  "amoxicillin",
  "amoxicillin-clavulanate",
  "Augmentin",
  "cephalexin",
  "cefdinir",
  "cefpodoxime",
  "doxycycline",
  "minocycline",
  "trimethoprim-sulfamethoxazole",
  "Bactrim",
  "nitrofurantoin",
  "ciprofloxacin",
  "levofloxacin",
  "moxifloxacin",
  "clindamycin",
  "metronidazole",
  "vancomycin",
  "linezolid",
  "oseltamivir",
  "Tamiflu",
  "acyclovir",
  "valacyclovir",
  "fluconazole",
  "nystatin",
  "sertraline",
  "fluoxetine",
  "escitalopram",
  "citalopram",
  "paroxetine",
  "venlafaxine",
  "duloxetine",
  "bupropion",
  "mirtazapine",
  "trazodone",
  "buspirone",
  "alprazolam",
  "lorazepam",
  "clonazepam",
  "diazepam",
  "zolpidem",
  "quetiapine",
  "olanzapine",
  "risperidone",
  "aripiprazole",
  "lamotrigine",
  "valproate",
  "carbamazepine",
  "levetiracetam",
  "topiramate",
  "sumatriptan",
  "rizatriptan",
  "ubrogepant",
  "rimegepant",
  "erenumab",
  "Aimovig",
  "fremanezumab",
  "Ajovy",
  "galcanezumab",
  "Emgality",
  "atogepant",
  "Qulipta",
  "nortriptyline",
  "amitriptyline",
  "protriptyline",
  "desipramine",
  "clomipramine",
  "venlafaxine XR",
  "desvenlafaxine",
  "Pristiq",
  "vilazodone",
  "Viibryd",
  "vortioxetine",
  "Trintellix",
  "lurasidone",
  "Latuda",
  "ziprasidone",
  "Geodon",
  "paliperidone",
  "Invega",
  "haloperidol",
  "chlorpromazine",
  "clozapine",
  "benztropine",
  "procyclidine",
  "amantadine",
  "lithium",
  "levothyroxine sodium",
  "liothyronine",
  "Cytomel",
  "enalapril",
  "ramipril",
  "quinapril",
  "benazepril",
  "irbesartan",
  "telmisartan",
  "eplerenone",
  "torsemide",
  "bumetanide",
  "hydralazine",
  "clonidine",
  "guanfacine",
  "doxazosin",
  "terazosin",
  "isosorbide dinitrate",
  "sacubitril-valsartan",
  "Entresto",
  "ivabradine",
  "Corlanor",
  "digoxin",
  "amiodarone",
  "sotalol",
  "flecainide",
  "propafenone",
  "dronedarone",
  "Multaq",
  "aspirin 81 mg",
  "clonidine patch",
  "metoprolol succinate",
  "metoprolol tartrate",
  "atorvastatin calcium",
  "icosapent ethyl",
  "Vascepa",
  "bempedoic acid",
  "Nexletol",
  "bempedoic acid ezetimibe",
  "Nexlizet",
  "niacin",
  "colesevelam",
  "Welchol",
  "cholestyramine",
  "warfarin sodium",
  "enoxaparin",
  "Lovenox",
  "heparin",
  "fondaparinux",
  "Arixtra",
  "ticlopidine",
  "cilostazol",
  "Pletal",
  "nitroglycerin sublingual",
  "pantoprazole sodium",
  "dexlansoprazole",
  "Dexilant",
  "rabeprazole",
  "lansoprazole",
  "ranitidine",
  "mesalamine",
  "Lialda",
  "Pentasa",
  "sulfasalazine",
  "balsalazide",
  "budesonide EC",
  "cholestyramine resin",
  "dicyclomine hydrochloride",
  "hyoscyamine",
  "linaclotide",
  "Linzess",
  "lubiprostone",
  "Amitiza",
  "plecanatide",
  "Trulance",
  "naloxegol",
  "Movantik",
  "methylnaltrexone",
  "Relistor",
  "naloxone",
  "Narcan",
  "buprenorphine-naloxone",
  "Suboxone",
  "naltrexone",
  "acamprosate",
  "disulfiram",
  "metformin ER",
  "saxagliptin",
  "Onglyza",
  "alogliptin",
  "Nesina",
  "repaglinide",
  "nateglinide",
  "acarbose",
  "miglitol",
  "insulin degludec",
  "Tresiba",
  "insulin detemir",
  "Levemir",
  "insulin regular",
  "insulin NPH",
  "semaglutide injection",
  "tirzepatide injection",
  "linagliptin-metformin",
  "Jentadueto",
  "sitagliptin-metformin",
  "Janumet",
  "empagliflozin-metformin",
  "Synjardy",
  "dapagliflozin-metformin",
  "Xigduo",
  "canagliflozin-metformin",
  "Invokamet",
  "fluticasone-salmeterol",
  "Advair",
  "budesonide-formoterol",
  "Symbicort",
  "mometasone-formoterol",
  "Dulera",
  "fluticasone-vilanterol",
  "Breo Ellipta",
  "umeclidinium-vilanterol",
  "Anoro Ellipta",
  "tiotropium-olodaterol",
  "Stiolto Respimat",
  "umeclidinium",
  "Incruse Ellipta",
  "roflumilast",
  "Daliresp",
  "prednisone taper",
  "benzonatate",
  "Tessalon",
  "guaifenesin",
  "dextromethorphan",
  "codeine-guaifenesin",
  "ceftriaxone",
  "cefazolin",
  "cefepime",
  "ceftazidime",
  "piperacillin-tazobactam",
  "Zosyn",
  "meropenem",
  "ertapenem",
  "imipenem-cilastatin",
  "ampicillin-sulbactam",
  "Unasyn",
  "amoxicillin clavulanate",
  "levofloxacin",
  "gentamicin",
  "amikacin",
  "cefuroxime",
  "aztreonam",
  "daptomycin",
  "ceftriaxone sodium",
  "clotrimazole",
  "ketoconazole",
  "itraconazole",
  "voriconazole",
  "posaconazole",
  "isavuconazole",
  "micafungin",
  "caspofungin",
  "oseltamivir phosphate",
  "zanamivir",
  "baloxavir",
  "Xofluza",
  "valganciclovir",
  "ganciclovir",
  "entecavir",
  "tenofovir",
  "emtricitabine",
  "dolutegravir",
  "bictegravir",
  "Biktarvy",
  "descovy",
  "truvada",
  "acamprosate calcium",
  "methotrexate",
  "hydroxychloroquine",
  "Plaquenil",
  "leflunomide",
  "sulfasalazine DR",
  "allopurinol",
  "febuxostat",
  "colchicine",
  "probenecid",
  "prednisolone acetate",
  "cyclosporine ophthalmic",
  "Restasis",
  "lifitegrast",
  "Xiidra",
  "latanoprost",
  "timolol ophthalmic",
  "brimonidine",
  "dorzolamide",
  "hydroxyzine",
  "cetirizine",
  "levocetirizine",
  "loratadine",
  "fexofenadine",
  "diphenhydramine",
  "famciclovir",
  "valacyclovir hydrochloride",
  "sildenafil",
  "tadalafil",
  "vardenafil",
  "tamsulosin",
  "finasteride",
  "dutasteride",
  "mirabegron",
  "Myrbetriq",
  "oxybutynin",
  "solifenacin",
  "trospium",
  "fesoterodine",
  "tolterodine",
  "estradiol",
  "progesterone",
  "medroxyprogesterone",
  "testosterone cypionate",
  "clomiphene",
  "letrozole",
  "anastrozole",
  "tamoxifen",
  "ondansetron ODT",
  "prochlorperazine",
  "dronabinol",
  "megestrol",
  "epoetin alfa",
  "darbepoetin alfa",
  "ferrous sulfate",
  "ferric carboxymaltose",
  "Injectafer",
  "iron sucrose",
  "Venofer",
  "cyanocobalamin",
  "folic acid",
  "cholecalciferol",
  "ergocalciferol",
  "calcitriol",
  "calcium carbonate",
  "calcium citrate",
  "potassium chloride",
  "magnesium oxide",
  "sodium bicarbonate",
  "phosphate binder",
  "sevelamer",
  "lanthanum carbonate",
  "amitriptyline hydrochloride",
  "nortriptyline hydrochloride",
  "acetazolamide",
  "topical tacrolimus",
  "tacrolimus ointment",
  "pimecrolimus",
  "Eucrisa",
  "crisaborole",
  "calcipotriene",
  "clobetasol",
  "triamcinolone",
  "betamethasone",
  "fluocinonide",
  "mupirocin",
  "silver sulfadiazine",
  "imiquimod",
  "podofilox",
  "valacyclovir tablets",
  "azelaic acid",
  "metronidazole gel",
];

export const CORE_MEDICAL_TERMINOLOGY = [
  "chief complaint",
  "history of present illness",
  "HPI",
  "review of systems",
  "ROS",
  "physical exam",
  "assessment and plan",
  "differential diagnosis",
  "problem list",
  "allergies",
  "medication reconciliation",
  "adverse effect",
  "contraindication",
  "black box warning",
  "prior authorization",
  "step therapy",
  "formulary",
  "quantity limit",
  "medical necessity",
  "baseline labs",
  "monitoring parameters",
  "follow-up interval",
  "return precautions",
  "shared decision-making",
  "informed consent",
  "evidence-based",
  "medication adherence",
  "treatment failure",
  "refractory disease",
  "clinical response",
  "partial response",
  "remission",
  "disease flare",
  "exacerbation",
  "acute",
  "subacute",
  "chronic",
  "progressive",
  "stable",
  "improved",
  "worsening",
  "bilateral",
  "unilateral",
  "proximal",
  "distal",
  "anterior",
  "posterior",
  "medial",
  "lateral",
  "superior",
  "inferior",
  "tenderness",
  "edema",
  "erythema",
  "induration",
  "ecchymosis",
  "ulceration",
  "lesion",
  "lesions",
  "macule",
  "papule",
  "plaque",
  "nodule",
  "vesicle",
  "pustule",
  "purpura",
  "petechiae",
  "lymphadenopathy",
  "hepatosplenomegaly",
  "jugular venous distension",
  "rales",
  "rhonchi",
  "wheezing",
  "crackles",
  "systolic murmur",
  "diastolic murmur",
  "neuropathy",
  "radiculopathy",
  "myelopathy",
  "arthralgia",
  "myalgia",
  "paresthesia",
  "dysesthesia",
  "allodynia",
  "hyperalgesia",
  "syncope",
  "presyncope",
  "orthostatic hypotension",
  "tachycardia",
  "bradycardia",
  "tachypnea",
  "hypoxemia",
  "hypoxia",
  "hypercapnia",
  "hyperglycemia",
  "hypoglycemia",
  "hyperkalemia",
  "hypokalemia",
  "hyponatremia",
  "acute kidney injury",
  "chronic kidney disease",
  "end-stage renal disease",
  "heart failure",
  "preserved ejection fraction",
  "reduced ejection fraction",
  "coronary artery disease",
  "atrial fibrillation",
  "chronic obstructive pulmonary disease",
  "asthma exacerbation",
  "obstructive sleep apnea",
  "gastroesophageal reflux disease",
  "inflammatory bowel disease",
  "ulcerative colitis",
  "Crohn disease",
  "psoriatic arthritis",
  "rheumatoid arthritis",
  "ankylosing spondylitis",
  "systemic lupus erythematosus",
  "multiple sclerosis",
  "myasthenia gravis",
  "ulcerative lesion",
  "cellulitis",
  "abscess",
  "sepsis",
  "bacteremia",
  "osteomyelitis",
  "venous thromboembolism",
  "deep vein thrombosis",
  "pulmonary embolism",
  "stroke",
  "transient ischemic attack",
  "prior authorization diagnosis",
  "supporting diagnosis",
  "diagnosis supporting prior auth",
  "step edit",
  "quantity override",
  "appeal letter",
  "letter of medical necessity",
  "peer to peer review",
  "benefit investigation",
  "specialty pharmacy",
  "infusion center",
  "home infusion",
  "biosimilar substitution",
  "drug holiday",
  "washout period",
  "loading dose",
  "maintenance dose",
  "induction dosing",
  "titration schedule",
  "dose escalation",
  "dose reduction",
  "renal dosing",
  "hepatic dosing",
  "pregnancy category",
  "lactation counseling",
  "teratogenicity",
  "adverse drug reaction",
  "serious adverse event",
  "drug drug interaction",
  "drug allergy",
  "medication intolerance",
  "needle phobia",
  "injection site reaction",
  "infusion reaction",
  "anaphylaxis",
  "angioedema",
  "urticaria",
  "pruritus",
  "desquamation",
  "lichenification",
  "fissure",
  "erosion",
  "excoriation",
  "scaling",
  "crusting",
  "oozing",
  "hyperpigmentation",
  "hypopigmentation",
  "post-inflammatory hyperpigmentation",
  "onycholysis",
  "onychomycosis",
  "paronychia",
  "alopecia areata",
  "androgenetic alopecia",
  "hidradenitis suppurativa",
  "atopic dermatitis",
  "seborrheic dermatitis",
  "contact dermatitis",
  "nummular eczema",
  "psoriasis vulgaris",
  "palmoplantar psoriasis",
  "inverse psoriasis",
  "scalp psoriasis",
  "psoriatic nail disease",
  "body surface area",
  "physician global assessment",
  "eczema area severity index",
  "investigator global assessment",
  "joint swelling",
  "joint effusion",
  "morning stiffness",
  "sacroiliitis",
  "enthesitis",
  "dactylitis",
  "uveitis",
  "tenosynovitis",
  "synovitis",
  "seropositive",
  "seronegative",
  "anti-cyclic citrullinated peptide",
  "antinuclear antibody",
  "double stranded DNA",
  "complement levels",
  "urine protein creatinine ratio",
  "albuminuria",
  "proteinuria",
  "hematuria",
  "nephrotic syndrome",
  "nephritic syndrome",
  "glomerulonephritis",
  "vasculitis",
  "granulomatosis with polyangiitis",
  "microscopic polyangiitis",
  "eosinophilic granulomatosis with polyangiitis",
  "temporal arteritis",
  "polymyalgia rheumatica",
  "giant cell arteritis",
  "Crohn's disease",
  "ulcerative proctitis",
  "proctosigmoiditis",
  "pancolitis",
  "fistulizing disease",
  "perianal disease",
  "mucosal healing",
  "endoscopic remission",
  "histologic remission",
  "extraintestinal manifestations",
  "opioid use disorder",
  "alcohol use disorder",
  "major depressive disorder",
  "generalized anxiety disorder",
  "bipolar disorder",
  "attention deficit hyperactivity disorder",
  "post-traumatic stress disorder",
  "obsessive compulsive disorder",
  "insomnia disorder",
  "somatic symptom disorder",
  "electronic prior authorization",
  "clinical documentation",
  "problem oriented charting",
  "medical decision making",
  "time-based coding",
  "cumulative time",
  "encounter time",
  "face-to-face time",
  "non face-to-face time",
  "care coordination time",
  "critical care time",
  "transitional care management",
  "chronic care management",
  "advance care planning",
  "shared notes",
  "chief concern",
  "interim history",
  "interval history",
  "medication side effects",
  "reviewed with patient",
  "patient education provided",
  "risk benefit discussion",
  "return to clinic",
  "follow up in",
  "emergency precautions",
];

export const COMMON_CLINICAL_ABBREVIATIONS = [
  "BP",
  "HR",
  "RR",
  "SpO2",
  "BMI",
  "CBC",
  "CMP",
  "BMP",
  "LFTs",
  "TSH",
  "A1C",
  "HbA1c",
  "LDL",
  "HDL",
  "TG",
  "ESR",
  "CRP",
  "ANA",
  "RF",
  "anti-CCP",
  "UA",
  "CXR",
  "CT",
  "MRI",
  "MRA",
  "EKG",
  "ECG",
  "EEG",
  "EMG",
  "NCS",
  "TTE",
  "TEE",
  "PFTs",
  "FEV1",
  "FVC",
  "ABG",
  "VBG",
  "NPO",
  "PO",
  "IV",
  "IM",
  "SQ",
  "PRN",
  "BID",
  "TID",
  "QID",
  "QD",
  "QHS",
  "AC",
  "PC",
  "q4h",
  "q6h",
  "q8h",
  "q12h",
  "QAM",
  "QPM",
  "QOD",
  "QWK",
  "QMO",
  "QYR",
  "SC",
  "SL",
  "INH",
  "neb",
  "NIV",
  "BiPAP",
  "CPAP",
  "RA",
  "WNL",
  "NAD",
  "A&O x3",
  "A&O x4",
  "SOB",
  "DOE",
  "PND",
  "LE edema",
  "GI",
  "GU",
  "MSK",
  "Neuro",
  "Derm",
  "HEENT",
  "ENT",
  "DTR",
  "MMSE",
  "PHQ-9",
  "GAD-7",
  "MOCA",
  "SLUMS",
  "FNA",
  "I&D",
  "LP",
  "DNR",
  "DNI",
  "POLST",
  "MOLST",
  "SNF",
  "LTAC",
  "ALF",
  "HHA",
  "EHR",
  "EMR",
  "ePA",
  "LOMN",
  "PAF",
  "NPI",
  "DEA",
  "BSA",
  "PASI",
  "EASI",
  "IGA",
  "DLQI",
  "DAS28",
  "CDAI",
  "SDAI",
  "MELD",
  "Child-Pugh",
  "eGFR",
  "BUN",
  "INR",
  "PT",
  "aPTT",
  "BNP",
  "NT-proBNP",
  "hs-CRP",
  "CPK",
  "CK",
  "troponin",
  "SOAP",
  "PA",
  "Dx",
  "Rx",
];

export const DEFAULT_GLOBAL_MEDICAL_VOCABULARY = dedupeTerms([
  ...MEDICAL_SPECIALTY_TERMS,
  ...BIOLOGIC_AND_ADVANCED_THERAPY_TERMS,
  ...COMMON_MEDICATION_TERMS,
  ...CORE_MEDICAL_TERMINOLOGY,
  ...COMMON_CLINICAL_ABBREVIATIONS,
]);
